(TeX-add-style-hook
 "regulatorio"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("book" "a5paper")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("geometry" "paperwidth=15cm" "paperheight=20cm") ("inputenc" "utf8") ("fontenc" "T1") ("babel" "spanish" "es-tabla") ("biblatex" "backend=biber" "style=numeric" "hyperref=true") ("xcolor" "table" "dvipsnames") ("caption" "font=small" "labelfont=bf" "labelsep=endash")))
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "book"
    "bk10"
    "geometry"
    "inputenc"
    "fontenc"
    "babel"
    "amsmath"
    "amssymb"
    "graphicx"
    "acronym"
    "float"
    "mathpazo"
    "fancyhdr"
    "tikz"
    "tkz-tab"
    "easyReview"
    "tgbonum"
    "csquotes"
    "imakeidx"
    "biblatex"
    "longtable"
    "xcolor"
    "titling"
    "needspace"
    "parskip"
    "hyperref"
    "tcolorbox"
    "empheq"
    "titlesec"
    "wasysym"
    "caption")
   (TeX-add-symbols
    '("chaptermark" 1))
   (LaTeX-add-labels
    "sec:tabladecontendos"
    "fig:activosdeuso"
    "fig:planeamiento-operativo"
    "fig:aumentotension"
    "fig:reducciontension"
    "fig:edac"
    "fig:edac1"
    "fig:edac2"
    "fig:ens"
    "fig:estructurainforme"
    "fig:insumoseventos"
    "fig:plazo1617"
    "fig:capacidad_conductores_emcali"
    "fig:ampacidad"
    "fig:eventogranmagnitud"
    "fig:mayor"
    "fig:reportes_transmision"
    "fig:mhaia"
    "eq:mhaia"
    "fig:capacidad"
    "fig:esquema"
    "fig:excluidos"
    "fig:gruposcalidad"
    "fig:valoressaidi"
    "fig:tiporele"
    "fig:proteccionestrafo"
    "fig:diagramatrafo"
    "fig:diagramatrafo1"
    "fig:zonas_diferencial"
    "fig:tiposfusibles"
    "fig:prueba"
    "eq:1"
    "fig:lineaat"
    "fig:caso1"
    "fig:caso2"
    "fig:caso3"
    "fig:fasores"
    "fig:gd"
    "fig:polaridadtransformadores"
    "fig:paralelo"
    "tab:valorestierraretie"
    "fig:tnsystem"
    "fig:tttisystem"
    "fig:capacidaddeconductores"
    "fig:pruebas"
    "fig:protocoloscomunicacion"
    "fig:capa7iccp"
    "fig:cabecera104"
    "fig:tramas104"
    "fig:formatoasdu"
    "fig:secuenciadeinterrogacion"
    "fig:comandos104"
    "fig:reco104diagrama"
    "fig:reco104"
    "fig:iec61850"
    "fig:iec61850_ln"
    "Ejemplos de nodos Lógicos"
    "fig:ln_example"
    "fig:iec61850resticcion"
    "fig:protocolosiec61850"
    "fig:arquitecturasubestacion"
    "fig:hsr"
    "fig:prp"
    "fig:centralgen"
    "fig:nlcentral"
    "fig:tnlcentral"
    "fig:tipoproyecto"
    "fig:plazo646"
    "fig:trabajoadistancia"
    "fig:trabajocontacto"
    "fig:trabajoapotencial"
    "fig:sui"
    "fig:impacto")
   (LaTeX-add-bibliographies
    "bibliografia")
   (LaTeX-add-acronyms
    "CND"
    "CNO"
    "COMTRADE"
    "DNA"
    "EDAC"
    "ENS"
    "FMECA"
    "FNCER"
    "LAC"
    "MC"
    "OR"
    "PENS"
    "RCM"
    "RETIE"
    "SAEB"
    "SDL"
    "SIN"
    "SP"
    "STN"
    "STR"
    "SOE"
    "UPME")
   (LaTeX-add-xcolor-definecolors
    "enlace"
    "titleblue"
    "titlegreen")
   (LaTeX-add-tcolorbox-tcbuselibraries
    "skins,breakable,listings,theorems"))
 :latex)

